import axios from "axios"
import Head from 'next/head'
import styles from '../../styles/About.module.css'
function About (movie){
    
    const url = "https://image.tmdb.org/t/p/w500/"+movie.poster_path
    const urlBackground = "https://image.tmdb.org/t/p/w500/"+movie.backdrop_path
    const title = movie.title

  
         return(
             <>
            <Head>
            <title>Movies-SSR </title>
            <meta name="description" content="Generated by create next app" />        
          </Head>
            <main>
            
                <div className={styles.background_fixed}  >
                    <img src={urlBackground}></img>
                </div>
                <div className={styles.conteiner_movie}>
                    <div className={styles.conteiner_movie__img}> 

                        <img className={styles.conteiner_movie__link} src={url} alt={title} />
                   </div>
                   <div className={styles.conteiner_movie__about}>
                        <div className={styles.conteiner_movie__title}>
                            <span>{movie.title}</span>
                        </div>
                        <div className={styles.conteiner_movie__subtitle}>
                            <span>{movie.release_date}</span>
                            <span className={styles.conteiner_movie__subtitle__leg}> ({movie.original_language})</span>        
                            <span> IMDb ({movie.vote_average}/10)</span> 
                        </div>
                        <div className={styles.conteiner_movie__sinopse}>
                            <span className={styles.conteiner_movie__sinopseTitle}>Sinopse</span>
                            <p className={styles.conteiner_movie__sinopseContent}>{movie.overview}</p>
                        </div>  
                  </div>
                </div>
            </main>
            </>
        )
}

About.getInitialProps = async (context) => {
    const { id } = context.query
     const {data} = await axios(`http://localhost:3000/api/movies/${id}`)
     
     return data.data
  }

export default About;