import axios from 'axios'
import Head from 'next/head'
import { Collection } from '../component/collections/Collection'

function Home({movies}) {

  return (
    <>
      <Head>
        <title>Movies-SSR </title>
        <meta name="description" content="Generated by create next app" />        
      </Head>
      <main>
        <section className="collections">
            <Collection movies={movies}/>
        </section>
      </main>
      </>
   

  )
}
Home.getInitialProps = async (context) => {
  const {data: {results}} = await axios("http://localhost:3000/api/movies")
  
  return {movies: results}
}

export default Home;